CREATE TABLE `invites` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(200) NULL DEFAULT NULL,
	`invite_user` VARCHAR(200) NULL DEFAULT NULL,
	`token` VARCHAR(200) NULL DEFAULT NULL,
	`complete` INT(11) NULL DEFAULT '0',
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;